name: MurderMystery
main: name.murdermystery.MurderMystery
version: "0.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - EconomyAPI
  - ScoreboardPlugin

permissions:
  MurderMystery.all:
    default: true
  MurderMystery.op:
    default: op