name: MurderMystery
main: main.java.name.murdermystery.MurderMystery
version: "0.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  killer:
    usage: /killer help
    description: "MurderMystery 游戏命令"
    permission: MurderMystery.a
    aliases:
      - 杀手
      - MurderMystery
  kadmin:
    usage: /kadmin help
    description: "MurderMystery 管理命令"
    permission: MurderMystery.b
    aliases:
      - 杀手管理
permissions:
  MurderMystery.a:
    default: true
  MurderMystery.b:
    default: op