name: Killer
main: name.killer.Killer
version: "0.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  killer:
    usage: /Killer help
    description: "killer游戏命令"
    permission: Killer.a
    aliases:
      - 杀手
  kadmin:
    usage: /kadmin help
    description: "killer管理命令"
    permission: Killer.b
    aliases:
      - 杀手管理
permissions:
  Killer.a:
    default: true
  Killer.b:
    default: op