name: KillerGame
main: name.killergame.KillerGame
version: "0.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  killer:
    usage: /killer help
    description: "killer游戏命令"
    permission: KillerGame.a
    aliases:
      - 杀手
  kadmin:
    usage: /kadmin help
    description: "killer管理命令"
    permission: KillerGame.b
    aliases:
      - 杀手管理
permissions:
  KillerGame.a:
    default: true
  KillerGame.b:
    default: op