name: MysteryMurder
main: name.mysterymurder.MysteryMurder
version: "0.0.1"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - AutoUpData

commands:
  killer:
    usage: /killer help
    description: "MysteryMurder 游戏命令"
    permission: MysteryMurder.a
    aliases:
      - 杀手
      - MysteryMurder
  kadmin:
    usage: /kadmin help
    description: "MysteryMurder 管理命令"
    permission: MysteryMurder.b
    aliases:
      - 杀手管理
permissions:
  MysteryMurder.a:
    default: true
  MysteryMurder.b:
    default: op